Feature/1121/archive story
operationstrategy/usergrid_python pull request #5
Opened 2017-10-26 19:50 UTC by karthiksuresh12

Archives entity to archive_entity table attaching all the relationships

2017-10-27 13:16 UTC, manchuck requested changes
Great work @karthiksuresh12 !  just some small changes and it's g2g.

Also please squash all these commits down and clean up the messages a bit

2017-10-27 13:16 UTC, manchuck commented on tests/test_usergrid.py
> +        tests archiving an entity
Tests archiving one entity

2017-10-27 13:16 UTC, manchuck commented on tests/test_usergrid.py
> +        )
Some more tests to write:

1. test_it_should_archive_one_entity_with_no_connections
2. test_it_should_not_archive_entity_when_conneting_entity_not_found

2017-10-27 13:16 UTC, manchuck commented on usergrid/usergrid.py
> +        if 'metadata' in entity:
woah no need to nest so much:


```
if 'metatdata' not in entity:
    return keys
```

2017-10-27 13:16 UTC, manchuck commented on usergrid/usergrid.py
> +        :param entity:
what type is entity?

2017-10-27 13:16 UTC, manchuck commented on usergrid/usergrid.py
> +        :param entity:
refactor to be entity_type and set the type

2017-10-27 13:16 UTC, manchuck commented on usergrid/usergrid.py
> +
extra line break for PEP8

2017-10-27 17:24 UTC, karthiksuresh12 reviewed
Done with the changes requested

2017-10-27 18:04 UTC, manchuck commented on tests/test_usergrid.py
> +        for key in ['connections', 'connecting']:
you dont need the loop here since you know that they exist you can just pop it directly

2017-10-30 14:52 UTC, manchuck requested changes
Almost there one more small change

2017-10-30 14:52 UTC, manchuck commented on usergrid/usergrid.py
> +            if key not in entity:
If is not needed in the for loop.  do the check beforehand and set it it an empty list

2017-10-30 14:52 UTC, karthiksuresh12 reviewed
Updated with changes requested .

2017-10-30 14:58 UTC, manchuck approved these changes
This is good.

We need clean up our mocked responses since this is a public repo but still this is good

2017-11-14 14:28 UTC, smitster approved these changes

2017-11-14 15:52 UTC, merged